remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "contrast"                 # try "air", "contrast", "dark", "dirt", etc.

title: Jan Hus Sermons - Czech originals and English translations
description: >-
  A digital edition of Jan Hus's Postil with the original Czech text and multiple English translations.
search: true

baseurl: /jan_hus_postila    # exactly my repo name, no trailing slash
url: ""                      # leave empty for GitHub Pages
masthead_title: true

markdown: kramdown

permalink: /sermons/:basename.html

# default front matter for everything in sermons/
defaults:
  - scope:
      path: ""                # apply to all files
    values:
      layout: single
      sidebar:                # this triggers the narrower content column
        nav: "main"           # optional â€“ we'll create a simple nav below
  - scope:
      path: "sermons"
    values:
      layout: sermon
      toc: true
      toc_label: "Contents"

header_pages:
  - title: About
    url: /about

plugins:
  - jekyll-include-cache
